/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _JS_CONFDEFS_H_
#define _JS_CONFDEFS_H_

#define CPP_THROW_NEW throw()
#define D_INO d_ino
#define ENABLE_YARR_JIT 1
#define HAVE_FORCEINLINE 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALECONV 1
#define HAVE_SNPRINTF 1
#define HAVE_WINSDKVER_H 1
#define HW_THREADS 1
#define JSGC_INCREMENTAL 1
#define JS_CPU_X86 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define JS_ION 1
#define JS_METHODJIT 1
#define JS_METHODJIT_TYPED_ARRAY 1
#define JS_MONOIC 1
#define JS_NUNBOX32 1
#define JS_POLYIC 1
#define MALLOC_H <malloc.h>
#define MOZILLA_UAVERSION "24.0"
#define MOZILLA_VERSION "24.2.0"
#define MOZILLA_VERSION_U 24.2.0
#define MOZJS_MAJOR_VERSION 24
#define MOZJS_MINOR_VERSION 2
#define MOZ_DEBUG_SYMBOLS 1
#define MOZ_DLL_SUFFIX ".dll"
#define MOZ_NTDDI_WIN7 0x06010000
#define MOZ_UPDATE_CHANNEL default
#define MOZ_WINSDK_TARGETVER 0x06010000
#define NEW_H <new>
#define NO_X11 1
#define NS_ATTR_MALLOC 
#define NS_WARN_UNUSED_RESULT 
#define RELEASE_BUILD 1
#define STDC_HEADERS 1
#define U_USING_ICU_NAMESPACE 0
#define WIN32 1
#define WIN32_LEAN_AND_MEAN 1
#define WINVER 0x502
#define XP_WIN 1
#define XP_WIN32 1
#define X_DISPLAY_MISSING 1
#define _CRT_NONSTDC_NO_WARNINGS 1
#define _CRT_NONSTDC_NO_WARNINGS 1
#define _CRT_NONSTDC_NO_WARNINGS 1
#define _CRT_NONSTDC_NO_WARNINGS 1
#define _CRT_SECURE_NO_WARNINGS 1
#define _CRT_SECURE_NO_WARNINGS 1
#define _CRT_SECURE_NO_WARNINGS 1
#define _CRT_SECURE_NO_WARNINGS 1
#define _WIN32_IE 0x0603
#define _WIN32_WINNT 0x502
#define _WINDOWS 1
#define _X86_ 1

#include "js/RequiredDefines.h"

#endif /* _JS_CONFDEFS_H_ */
